---
title: "First Street data"
author: "Alan Jackson"
format: html
editor: source
---

##   work out basics of a report using First Street data


```{r}
# setup

library(tidyverse)
library(gt)
library(tidycensus)

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"
output_path <- "/home/ajackson/Dropbox/projects/CeationCareTaskforce/FirstStreetFlood/"

#   Some useful data

Census <- readRDS(paste0(path, "Census_data_for_Texas_by_tract.rds"))

FSF <- read_csv(paste0(path, "FSF_Flood/fsf_flood_tract_summary.csv")) %>% 
  rename(GEOID=fips)

#   Add polygons and census data

FSF <- inner_join(FSF, Census, by="GEOID") %>%
  sf::st_as_sf() %>% 
  sf::st_make_valid()

FSF_Harris <- FSF %>% 
  filter(stringr::str_starts(GEOID, "48201"))

```

##        Most vulnerable tracts

```{r}
FSF_Harris <-  FSF_Harris %>% 
  mutate(severe=count_floodfactor7 + count_floodfactor8 + count_floodfactor9 +
           count_floodfactor10) %>% 
  filter(Households>100) %>% 
  mutate(Flood_ratio=severe/Households)  

FSF_Harris %>% 
  # filter(severe<1500) %>% 
  arrange(-severe) %>%  head(25) %>% 
  ggplot(aes(x=severe)) +
  geom_histogram(bins=40)

FSF_Harris %>% 
  # filter(Flood_ratio<0.1) %>% 
  arrange(-Flood_ratio) %>%  head(25) %>% 
  ggplot(aes(x=Flood_ratio)) +
  geom_histogram()

FSF_Harris
```

##        Map tracts with Flood_ratio > 1

```{r}

Top_tracts <- FSF_Harris %>% 
  filter(Flood_ratio>0.75) %>% 
  mutate(Label=paste("Harris", row_number()))

# Map of blkgrp
  

tmap::tmap_mode("view") # set mode to interactive plots
tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tm_shape(Top_tracts) + 
  tmap::tm_fill(col = "red", title = paste("Blkgrp"), alpha=0.2, style="pretty")+
  tmap::tm_borders(lwd=0.4) 


#   Index map of frequent flier blkgrps

box <- Top_tracts %>%
    sf::st_bbox() %>% 
    expand_box(., 0.4)
  box["xmin"] <- box["xmin"] - 0.5
  box["xmax"] <- box["xmax"] + 0.1
  
  Base_basemapR <- basemapR::base_map(box, basemap="mapnik", increase_zoom=2)
  
 # Index_map <-
   Top_tracts %>% 
   # inner_join(., FreqFliers, by="censusBlockGroupFips") %>% 
   # arrange(censusBlockGroupFips) %>% 
   # sf::st_as_sf() %>% 
    ggplot() +
    Base_basemapR +
   geom_sf(color="black", fill="red", alpha=0.2)+
   ggrepel::geom_label_repel(
    aes(label = paste(Label), geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0.0,
    size=2,
    force = 10
  ) +
    labs(title=paste("Harris County"),
         subtitle="Census Tracts with >75% Severe Flood Factor",
         x="Longitude",
         y="Latitude") +
    scale_x_continuous(breaks = seq(-96.2, -94.8, by = 0.4)) +
    theme(title =element_text(size=8),
         subtitle =element_text(size=6)
          ) +
    coord_sf(xlim=c(box$xmin, box$xmax),c(box$ymin, box$ymax)) 
   
   ggsave("FS_Harris.png", width=3.5, height=3, units="in")
   
#   Table
   
   Summary_table <- Top_tracts %>% 
     sf::st_drop_geometry() %>% 
   arrange(GEOID) %>% 
  select(GEOID, Label, Pop_tractE,
         Households, Med_incE) %>% 
  gt() %>%     
  gt::tab_header(
      title="First Street Flood Factor Severe",
      subtitle=paste("Harris County, Tracts  over 75%")
    ) %>% 
    cols_label(
      GEOID="Tract",
      Label="Label",
      Pop_tractE="Pop",
      Households="Households",
      Med_incE="Med Income"
    ) %>% 
    fmt_currency(
      columns = Med_incE,
      decimals=0
    ) %>% 
    tab_footnote(
      footnote=md("*2020 census data*")
    )  

Summary_table %>% tab_options(., container.width=800, container.height=800) %>% 
  gtsave("FS_Harris_table.png") 

   
   
# }
```







